### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by lorenzobalzani** [HelmutQualtinger/RepubblicaScraping#1]
I am on a quest to scrape finance articles from La Repubblica, so this code would be helpful. However, there is neither a README nor any indications of its capabilities. What is the intended use of the code, and what can it achieve? @HelmutQualtinger

**Comment by HelmutQualtinger** [comment]
Non mi sono reso conto che avevo fatto pubblico questo progettino su github.

Era solo un esercizio auto educativo per capire come funziona  beautiful
soup per scannerizzare uno dei giornali che leggo regolarmente, per trovare
subito gli articoli nuovi. Mi mando un email una volta al giorno con i link
di articoli nuovi. Lo faccio per mantenere il mio livello d'italiano anche
se ormai vivo al estero.

 Non distribuisco l' informazione raccolta. Ed esclusivamente per uso
privato.

Ci sono un sacco di tutorial su YouTube sotto la voce beautiful soup.

 Cordiali saluti

     Helmut in Arte





Lorenzo Balzani ***@***.***> schrieb am Di., 30. Jan. 2024,
12:34:

**Comment by HelmutQualtinger** [comment]
Ps per raccolta più completa dei dati bisogna usare una cosa come selenium
per captare anche i contenuti generati dinamicamente da JavaScript. E un
po' più esigente ma anche su selenium si trova tutto su YouTube e github.

Buona fortuna nella caccia al tesoro

Helmut in arte

Lorenzo Balzani ***@***.***> schrieb am Di., 30. Jan. 2024,
12:34:

**Comment by lorenzobalzani** [comment]
Grazie Helmut per i consigli!

Buona giornata ;)

**Comment by HelmutQualtinger** [comment]
Lorenzo's friendly interest made me feel obliged to provide a short explanation in the README and I gave the dependencies for pip or pipenv in Pipefile and requirements.
